# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0002_employeeprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=30, unique=True)),
                ('institution', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
