# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0003_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degreename',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='degree',
            name='institution',
            field=models.CharField(max_length=20),
        ),
    ]
