# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0004_auto_20180508_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='portfolio',
            field=models.CharField(max_length=30),
        ),
    ]
