# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0006_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
    ]
