# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0007_skill_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainingname', models.CharField(max_length=20)),
                ('institute', models.CharField(max_length=30)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile')),
            ],
        ),
    ]
