# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0010_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='portfolio',
            field=models.URLField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
