# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0011_auto_20180604_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
    ]
