# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0013_auto_20180617_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.EmployeeProfile'),
        ),
    ]
