# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 02:37
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=40)),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
