# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0002_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companyprofile.Vacancy')),
            ],
        ),
    ]
