# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 07:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0005_auto_20180509_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
