# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0007_auto_20180606_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companyprofile.Companyprofile'),
        ),
    ]
