# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 07:58
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companyprofile', '0008_auto_20180612_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=ckeditor.fields.RichTextField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.CV'),
        ),
        migrations.AlterField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyprofile.Vacancy'),
        ),
    ]
